import SiteHeader from "../components/SiteHeader";
import SiteFooter from "../components/SiteFooter";
import ResourceLibrary from "./ResourceLibrary";
import {learnData} from "./learnData";
import "./learn.css";

export const metadata={title:"FURKID Learn｜寵物照護專業進修資源庫",description:"整理台灣寵物保母、行為訓練、寵物急救、營養鮮食、高齡照護等進修課程與專業書單，協助照護者找到值得學的下一步。",alternates:{canonical:"/learn"},openGraph:{title:"FURKID Learn｜寵物照護專業進修資源庫",description:"找課程、查進修資源、讀專業書，建立自己的寵物照護學習路徑。",url:"/learn",type:"website"}};
const areas=[["01","進修課程","108 筆課程，保留主辦單位、時數、費用、認證與來源。","#library"],["02","專業書單","299 本參考書單，依照護領域整理。","#library"],["03","證照與認證","逐步整理不同證照、時數與培訓制度。","#certifications"],["04","FURKID Original","電子書、線上課程、工具包與工作坊；商品內容留在 FURKID。","#original"]];
export default function Learn(){return <main><SiteHeader/><section className="section-hero shell learn-hero"><span>LEARN / PROFESSIONAL DEVELOPMENT</span><h1>找到值得學的，<br/>也找到下一步怎麼學。</h1><p>FURKID Learn 是寵物照護專業進修資源庫。從寵物保母、行為、急救、營養到高齡照護，把分散的課程與專業書單整理成可查找、可核實、持續更新的學習入口。</p><div className="learn-stats"><div><b>{learnData.courses.length}</b><span>進修課程</span></div><div><b>{learnData.catOrder.length}</b><span>專業領域</span></div><div><b>{learnData.books.length}</b><span>參考書單</span></div></div></section><section className="section-body shell"><div className="section-head"><span>EXPLORE</span><h2>公開知識，讓專業更容易開始。</h2><p>課程、主辦單位、日期、認證資訊、書單與來源維持公開。未來 Unlock 用在收藏、追蹤、通知與個人學習清單，而不是把公開知識鎖起來。</p></div><div className="learn-grid">{areas.map(x=><a className="learn-card" href={x[3]} key={x[0]}><small>{x[0]}</small><h3>{x[1]}</h3><p>{x[2]}</p><span>探索 →</span></a>)}</div></section><section className="learn-library" id="library"><div className="shell"><div className="section-head"><span>RESOURCE LIBRARY</span><h2>407 筆進修資源，現在可以直接搜尋。</h2><p>完整保留原資源庫 108 筆課程與 299 本書單。可切換課程／書單、依六大領域篩選，或直接搜尋名稱、主辦單位與作者。</p></div><ResourceLibrary courses={learnData.courses} books={learnData.books} categories={learnData.catOrder}/><div id="certifications"></div></div></section><section className="learn-original" id="original"><div className="shell split"><div><span className="tag">FURKID ORIGINAL</span><h2>不只整理資源，也把實務經驗做成可以帶走的工具。</h2><p>電子書、線上課程、工具包與工作坊會有自己的 FURKID.ME 商品頁。現階段付款按鈕可導向 Portaly；未來更換自有金流時，不需要重做商品頁與 SEO 資產。</p></div><div className="paper"><div className="paper-top">ORIGINAL / COMING NEXT</div><h3>新手寵物保姆<br/>接案攻略</h3><p>從準備、溝通、服務流程到開始接案，建立第一套可以實際執行的方法。</p><small>商品介紹留在 FURKID.ME<br/>Checkout 暫由 Portaly 處理</small></div></div></section><section className="service-cta"><div className="shell"><span>MY FURKID / FUTURE</span><h2>知識公開，個人化才 Unlock。</h2><p>未來免費帳號承接收藏、追蹤、新梯次通知與我的學習清單；FURKID+ 保留給真正需要進階決策與個人化能力的功能。</p></div></section><SiteFooter/></main>}
